// <auto-generated />
using System;
using Logwarts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Logwarts.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231118175814_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Logwarts.Model.LogEntryModel", b =>
                {
                    b.Property<int>("LogEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogEntryId"));

                    b.Property<int>("MetaDataId")
                        .HasColumnType("int");

                    b.Property<string>("commit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("resourceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("spanId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("traceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogEntryId");

                    b.HasIndex("MetaDataId");

                    b.ToTable("LogEntryModel");
                });

            modelBuilder.Entity("Logwarts.Model.MetaDataModel", b =>
                {
                    b.Property<int>("MetaDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MetaDataId"));

                    b.Property<string>("parentResourceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MetaDataId");

                    b.ToTable("MetaDataModel");
                });

            modelBuilder.Entity("Logwarts.Model.LogEntryModel", b =>
                {
                    b.HasOne("Logwarts.Model.MetaDataModel", "metadata")
                        .WithMany()
                        .HasForeignKey("MetaDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("metadata");
                });
#pragma warning restore 612, 618
        }
    }
}
